### ISSUE TITLE
new students unknown to system before registration

### ISSUE THREAD

**Issue by gregbaker** [sfu-fas/coursys#106]
Until students register for courses, we don't generally have any interest in them, so they aren't imported into the system. This causes problems with forms, notably prereq waivers and the CMPT 120 placement test which must be done before registration.

Proposal: duplicate a query from the grad importer to find all students who have accepted applications (into FAS programs). Do import_person on that group as part of the nightly import.

**Comment by philb61** [comment]
That's another possible solution to #60 (and vice-versa).
