### ISSUE TITLE
sharing TUGs to school TA admins who didn't appoint the TA

### ISSUE THREAD

**Issue by sfumo** [sfu-fas/coursys#116]
CS needs to manage Cynthia Xie's CHIN course TUGs even though we don't appoint or pay the TAs.  Tracy said she also asked why when this came up, but says we still have to.  Cynthia can (did) log on and make a TUG but of course Tracy and Janet can't see it.

most of the courses are acad_group=APSC, acad_org=LTI. they are the only such courses right now but that's not guaranteed.  CHIN  180, 181, 182, 190, 191, 280, 281, 290, 291.  Cynthia also mentions 390, but it is acad_group=ARTS so that may already be an exception. or an error.  identifying the courses automatically may be unreliable.

Tracy asked that these courses be added to the CS TA postings BUT ALSO not be listed on the posting to be ranked.   on discussion, she agreed she really just needs them to show up for her under /tugs .

could be generally useful: a mechanism for anyone who creates a TUG to make it available to someone else,
Tracy likes the idea of having Cynthia open/assign/share her TUGs to a role (CMPT / TA Administrator).  

for depts that don't manage TAs there, they won't have such a role, so if we wanted it available that way, sharing to SFU individuals would be wanted.

**Comment by gregbaker** [comment]
This seems to be taking care of itself: closing. If there's demand, we can look at it again.
