### ISSUE TITLE
Able to access course pages without authentication

### ISSUE THREAD

**Issue by sl0wc0der** [sfu-fas/coursys#225]
https://coursys.sfu.ca/2022su-cmpt-479-d1/ is forbidden
but can access https://coursys.sfu.ca/2022su-cmpt-479-d1/pages without auth.

Even this: https://coursys.sfu.ca/2022fa-cmpt-732-g1/pages/
Can also access this without any login. And can further look into the details.

Not sure if it's intended behavior

**Comment by gregbaker** [comment]
This is the intended behaviour: instructors can choose visibility on each page
