### ISSUE TITLE
Discussion Forum entry is not show

### ISSUE THREAD

**Issue by harry-sunhao** [sfu-fas/coursys#232]
When the course only activated the discussion forum and no pages and group activity, the forum entry is not shown on the course information page for students.

if I add code in _coursys/templates/grades/course_info_student.html_ line 9
change `{% if any_group or has_index or course.discussion%}`
to `{% if any_group or has_index or course.discussion or forum_enabled%}`

I am not sure this change is OK for other things.

**Comment by skyemason** [comment]
Hey! Thanks for this. :) We've made this change.
