### ISSUE TITLE
New Advisors created using the Dept. Admin interface have their Department's Unit, rather than APSC.

### ISSUE THREAD

**Issue by classam** [sfu-fas/coursys#26]
Not sure how to fix this in a way that's not Bad For Interoperability With Other Departments.

**Comment by philb61** [comment]
This only affects the FAS schools.  With the new role request form, and the fact that DAs can fill it out to ask the FAS director/DA to add the roles, this is hardly an issue anymore.

Like Curtis, I can't think of a way to fix this, short of hardcoding checks per unit, that won't break the other units presently using the system.
