### ISSUE TITLE
Feature Request: Opt in to seeing your grade in the assignment graded notification email

### ISSUE THREAD

**Issue by JetSimon** [sfu-fas/coursys#289]
Hello,

I like Coursys a lot more than Canvas, however one thing I miss is that on Canvas I can opt in to seeing my grade in my email when it is released.

I'd like to put in a request for this feature to be added if possible.

Thank you,

Jet

**Comment by gregbaker** [comment]
Emails are sent to students by default when grades are released. I think the only reason they wouldn't be is user opt out: https://coursys.sfu.ca/config/news

**Comment by JetSimon** [comment]
Sorry @gregbaker, to be more specific I meant I was wondering if said emails would be able to have the grade percentage included in them. As that is a nice QoL thing.
