### ISSUE TITLE
Advising Artifacts and Course Notes management

### ISSUE THREAD

**Issue by philb61** [sfu-fas/coursys#32]
Ideally, things that should be possible:

Move an artifact into a proper course note (e.g. many artifacts got created for courses that do already exist.  These (and any news ones that also now exist in SIMS) should be moved under the correct courses.  Current workaround:  Copy and pasting the note in the artifact. If not possible, keep copying and pasting, but have an advisor function to delete the artifact.

Merge multiple artifacts:  Many similar artifacts can be combined.  For example, there is "Math third repeat" artifact, a "course repeats" artifact (which contains info about a student repeating math 232 for the third time).  These really should be combined.

**Comment by gregbaker** [comment]
Lots of changes to advising since this request. Closing since it should have been handed by other refactoring.
