### ISSUE TITLE
Mark comments should support links

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-fas/coursys#35]
The comments field for marks should support links to other pages, particularly GitLab.  I just completed marking a course with projects on GitLab and linked to commits, issues, discussions, and even specific lines.  The URLs were just copied into the text, not live.  I would really have benefitted from being able to specify something like (for example, in MarkDown syntax) [dbinstance.py, line 32](https://gitlab.cs.sfu.ca/student-name/project-name/master/dbinstance.py#L32).  I'm not picky about they syntax, so long as I have the ability to specify a more readable print string and a full URL.

The easier we make it for student to follow our comments, the more they will follow up and learn from them.

**Comment by gregbaker** [comment]
Marking comments are currently treated like plain text (with line breaks preserved).

Option 1: run the comments through the django urlize filter to at least make URL-like things clickable.

Option 2: Let the marker toggle "I'm going to use markdown", record that as part of the ActivityMark object, and display appropriately.

I see no downside to doing 1 right away, but 2 might be worth it in the longer term.

**Comment by tedkirkpatrick** [comment]
Just allowing links (Option 1) would be a good start.  I think Option 2 (switching to a more complete markup solution) would be great *provided* it was done system-wide.  For example, news items and discussion pages would support the same format.  The current welter of formats confuses me.

**Comment by philb61** [comment]
Will modify this to allow URLs and to also preserve linebreaks.  Keep in mind that the urlize filter will also make any email address clickable with a mailto: link.

**Comment by tedkirkpatrick** [comment]
[I’m trying an email reply to see if this gets added to the GitHub comment thread.]

On May 21, 2015, at 1:21 PM, Phil Boutros <notifications@github.com> wrote:

> Will modify this to allow URLs and to also preserve linebreaks. Keep in mind that the urlize filter will also make any email address clickable with a mailto: link
> 
> 
Fine.  In all these cases, as a user I like to see short summary line underneath the text box, describing what formats will be transformed and how to escape them.  I’m happy to write that, working with you to figure out how the system works and summarize it.

Ted

**Comment by philb61** [comment]
It's pushed to prod now.  Really, there is no interaction required, it will automagically urlize things that look like URLs.  You can see the documentation here:
