### ISSUE TITLE
Support aliases when sending emails

### ISSUE THREAD

**Issue by philb61** [sfu-fas/coursys#40]
When sending emails (for example, advisor notes that are also emailed to the students), could we use an email alias instead (for example, bob_foo@sfu.ca instead of bfoo@sfu,ca)?  This could be handy, specially in the case of people who have an ID with their maiden name, but aliases with their new name, as students often don't associate their IDs with the advisor.

**Comment by gregbaker** [comment]
coredata.models.Person.config['email'] is honoured if set. There is currently no UI to set it.

**Comment by philb61** [comment]
That should be good enough for the few cases where we need to change it.  If anything, it should be maybe added to the sysadmin system only so users don't bugger up their own email setting.
