### ISSUE TITLE
Course information page with different TA address still shows part of TAs email address

### ISSUE THREAD

**Issue by philb61** [sfu-fas/coursys#43]
If you have a course information page where a TA address is defined, the students can still see the first part of all the TAs' email addresses.  I would suspect the correct behaviour is to not show their email address at all.

**Comment by gregbaker** [comment]
The current behaviour us to show students "userid@". That was done as a balance between "this is the easy way to contact the TA" and "you have no way to figure out how to contact the TA". I'd suggest a WONTFIX unless evidence suggests pain and suffering.

**Comment by philb61** [comment]
Sounds sane to me.  Marking it WONTFIX.
