### ISSUE TITLE
Query on CMPT 225 doesn't sort by instructor

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-fas/coursys#44]
I just searched for all instances of CMPT 225 in the database (N=30) (https://courses.cs.sfu.ca/browse/#!number=225&subject=CMPT).  I can sort by column by clicking on the Semester and Campus column headings but when I click on "Instructor(s)", it doesn't sort. The little icon shows that CourSys thinks the column is sorted in either ascending or descending order but the data don't change.

**Comment by gregbaker** [comment]
This is likely to be a WONTFIX. The django_datatables_view module that powers everything really insists on sorting in the database (i.e. ORDER BY...). Instructors aren't there to order by: another table must be joined to get them.

Option 1: add a denormlized "instructor_sort" column to courseofferings. Option 2: a tricky subclass override on the ordering logic that special-cases that column and sorts in Python and kind-of works like the other sorting, but probably not entirely. Neither seems particularly fun.

**Comment by tedkirkpatrick** [comment]
Makes sense.  Can you remove the "sort" icon from the column header?
