### ISSUE TITLE
"Section number" field in "Browse Course Offerings" query should be case-insensitive

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-fas/coursys#49]
When I search on an evening section using "e100", it is not found.  Querying with "E100" finds it.

**Comment by philb61** [comment]
For some reason, searching on my local, dev machine yields the same results regardless of case for the section, but prod does not.  I wonder if there's something weird in the SIMS Metadata...

Will have to look at this.

**Comment by gregbaker** [comment]
The search in dev uses whoosh, but production uses elasticsearch. It could be elasticsearch being case-sensitive, but that doesn't sound right.

**Comment by gregbaker** [comment]
Previous comment was a damn stupid lie. Fixed by 5fc9fff0b96a3620d3cfe5add90f129776d2842f and pulled on production
