### ISSUE TITLE
Fix Signals/Logging in tacontracts

### ISSUE THREAD

**Issue by classam** [sfu-fas/coursys#5]

**Comment by gregbaker** [comment]
I don't know what this means. Therefore it is unimportant.

**Comment by classam** [comment]
Instead of directly logging every .save, tacontracts used django signals ( https://docs.djangoproject.com/en/1.8/topics/signals/ ) to automatically bind a log event to things happening to the database.

Well, at least, it was supposed to. It never actually worked. 

Which means that it's a safe bet to kill this file: https://github.com/sfu-fas/coursys/blob/master/tacontracts/signals.py
