### ISSUE TITLE
Allow recording info about faculty appointments before person is known

### ISSUE THREAD

**Issue by gregbaker** [sfu-fas/coursys#54]
Data about a position is generally known before there is a person to associate it with (e.g. during the hiring process). Faculty module needs to be able to store this, and migrate it to a real faculty member once they are known.

**Comment by gregbaker** [comment]
Suggested strategy for implementation: implement a NewFacultyMember (or something) model that stores things that are known that will later become an Initial Appointment event for a person.

Add functionality that turns that into an Initial Appointment event for a specific person once they are hired.

**Comment by philb61** [comment]
This is done and deployed.
