### ISSUE TITLE
TUG total times have ridiculously precise values

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-fas/coursys#63]
The TUG for my TA (https://courses.cs.sfu.ca/2015fa-cmpt-225-d2/config/tugs/wpa10/) lists a "Required total hours" of "167.4000000000000003552713679".  Sometimes precision is a good thing ... but sometimes it's not.

**Comment by gregbaker** [comment]
WONTFIX. Some instructors need to schedule their TAs to the picosecond.

**Comment by tedkirkpatrick** [comment]
> On Aug 25, 2015, at 8:48 PM, Greg Baker <notifications@github.com> wrote:
> 
> WONTFIX. Some instructors need to schedule their TAs to the picosecond.
> 
> 
There’s a TSSU grievance in there, I do believe.

Ted
