### ISSUE TITLE
Add "no grades assigned" and "xx% graded" to instructor's and TA's grade statuses

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-fas/coursys#75]
An enhancement to help the instructor see grading status at a glance: Add two new statuses, visible only to the TA and instructor, reading "no grades assigned" and "xx% graded".  An assignment's status would go from "due date not passed" (removing the "no grades:" prefix) to "no grades assigned" (or perhaps "ready for grading") once the deadline passes.  After at least one grade has been assigned, the status would change to "xx% graded", where "xx" is the percent of enrolled students who have had grades assigned.

For students, the status would remain "grades not released to students", only changing to "grades released" when the grades were released.

When supervising multiple TAs, each taking alternate assignments, this sort of overview is invaluable. It can also jog the instructor's memory when they forget that they were responsible for grading something rather than the TA.

**Comment by philb61** [comment]
See get_status_display in grades/models.py (line: 189)
