### ISSUE TITLE
Sharing Discussions Across Courses

### ISSUE THREAD

**Issue by nsumner** [sfu-fas/coursys#91]
It can be beneficial to share discussion forums or discussion topics across courses. For instance, a cross-listed course can place graduate and undergraduate students in different courses with different discussion forums even when they ought to be able to converse. It may be desirable to control this at the topic granularity.

**Comment by gregbaker** [comment]
We can straight-up combine cross-listed courses into a single "section". That combines grading and everything else. Does that solve your problem?

If not, then this is a pretty significant refactor in the discussion module.

**Comment by nsumner** [comment]
That would actually be perfect! I didn't realize that was an option, so I was offering more of a 'pie in the sky' or 'nice to have' feature.

**Comment by gregbaker** [comment]
I just added a note to advertise the combined offering feature, so instructors have a hope of hearing about it. I'm going to say d1be367 closes this as well.
