### ISSUE TITLE
Add wrapping styles for <pre> tags

### ISSUE THREAD

**Issue by csvenja** [sfu-fas/coursys#92]
On desktop:
<img width="1390" alt="desktop" src="https://cloud.githubusercontent.com/assets/2884831/12834356/a0ae2456-cb5b-11e5-8295-d61062e05be4.png">

On mobile:
![mobile](https://cloud.githubusercontent.com/assets/2884831/12834357/a22dce12-cb5b-11e5-99d7-d671d5b77352.PNG)

Worse for multiple long lines. Scrolling the whole page over and over again is a pain.

Here are two solutions with possible cons, not sure which one is better:
```overflow: scroll```: auto hide scrollbar on code block, user may miss info in overflowed area
```white-space: pre-wrap```: wrap at space won't work for no-break lines (which I haven't seen yet), user may miss line-break or space at the end of line

**Comment by yzheng624** [comment]
:shipit:

**Comment by gregbaker** [comment]
Thanks @csvenja for pointing that out.
